server:
  port: 9086
  servlet:
    context-path: /reward
spring:
  application:
    name: healthify-reward
  config:
    import: "optional:configserver:http://localhost:8888"
    label: default
  cloud:
    discovery:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: reward-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  instance:
    prefer-ip-address: true
