spring:
  profiles:
    active: native
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:healthifydb}?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:Wellness36@}
    hikari:
      auto-commit: true
      connection-timeout: 20000
      idle-timeout: 30000
      max-lifetime: 120000
      maximum-pool-size: 3
      minimum-idle: 1
  liquibase:
    change-log: "classpath:/db/db.changelog-master.xml"
health:
  gateway:
    url: localhost:8085
eureka:
  eurekaServer:
    port: 8061
  client:
    service-url:
      defaultZone: http://localhost:8061/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  endpoints:
    enabled-by-default: true
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
      exposure:
        include: "*"
        exclude:
          - env
---
management:
  endpoints.web.exposure.include: "*"
  endpoint:
    health:
      show-details: always
